CREATE DATABASE misnotas
	DEFAULT CHARACTER SET utf8;

USE misnotas;

CREATE TABLE usuarios (
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	nombre VARCHAR(25) NOT NULL UNIQUE,
	clave VARCHAR(255) NOT NULL UNIQUE,
	email VARCHAR(40) NOT NULL UNIQUE,
	fecha_registro DATETIME NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE nodos(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	id_usuario INT NOT NULL,
	id_padre INT,
	nombre VARCHAR(30) NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(id_usuario)
		REFERENCES usuarios(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
);

CREATE TABLE notas(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	id_nodo INT NOT NULL,
	descripcion VARCHAR(40) NOT NULL,
	texto TEXT CHARACTER SET utf8 NOT NULL,
	fecha_creacion DATETIME NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(id_nodo)
		REFERENCES nodos(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
);